### ISSUE TITLE
tip for the webpack chapter

### ISSUE THREAD

**Issue by UnsungHero97** [verekia/modern-js-stack-training#6]
It might be useful to add a tip to the webpack chapter about using ES6 syntax for `webpack.config.js`. All it takes is to rename the file to `webpack.config.babel.js`, and then you use standard ES6 syntax, including `import` and `export`:

```
import Webpack from 'webpack';

import pkg from './package.json';

...

export default {
  entry: ...,
  output: { ... },
  module: { ... },
  ...
}
```

**Comment by verekia** [comment]
I didn't know that, thanks for the tip! Will update the tutorial asap. I found that it's also possible with `gulpfile.babel.js`, pretty neat :)

**Comment by verekia** [comment]
Fixed! Thank you very much :)

**Comment by UnsungHero97** [comment]
Anytime :) I just went through this exercise not too long ago... was a bit overwhelmed by everything. There's certainly a place for a well put-together guide on getting started with a modern JS stack, or rather, putting one together from scratch.

**Comment by saitonakamura** [comment]
ES6 is awesome but using `import` can cause problems.
For example [this file](https://github.com/saitonakamura/saitonakamura-react-boilerplate/blob/master/server.js) is executed by node, like `node --harmony server.js` and I'm using it to enable hot reloading.
But I can't use `import` in here because node `harmony` mode does not support `import` and the main cause of this that there is problems with implementation `import` in V8, [see this thread](https://bugs.chromium.org/p/v8/issues/detail?id=1569).
So I'm still using `require` in code that executes on server (such as using js wrappers for `webpack`, `webpack-dev-middleware`, `webpack-hot-middleware`) and recommend you to do so.
AFAIK you *can* use `export`, but I find it violating the POLA to use `export` and not to use `import` in one file.
Other cool features like `const`, `let` are available using `--harmony` flag by the way.

**Comment by verekia** [comment]
@saitonakamura This is why I use Babel on the server as well. Every `import` in this tutorial ends up as a `require` in the `lib` directory, even server code.
